YDA-5699 add admin page
UtrechtUniversity/yoda-portal pull request #314
Opened 2024-06-05 13:36 UTC by FuHsinyu

YDA-5699
Added the blueprint admin.py and template/index.html for an empty admin page.
Added CSS file in the static folder for the admin page

2024-06-05 14:01 UTC, lwesterhof commented
Congratulations on your first PR! 🎉

2024-06-11 06:32 UTC, lwesterhof requested changes

2024-06-11 06:32 UTC, lwesterhof commented on admin/admin.py
> +__copyright__ = 'Copyright (c) 2021, Utrecht University'
2021 -> 2024

2024-06-11 06:32 UTC, lwesterhof commented on admin/static/admin/css/admin.css
For now we don't need this CSS file. We will try to do all the layout with the https://getbootstrap.com/ framework, only with exception we will add custom CSS. This ensures that the whole of Yoda plays nice with themes.

2024-06-11 06:32 UTC, lwesterhof commented on admin/templates/admin/admin.html
> +{% block title %}{{ super() }} &dash; Administrition{% endblock title %}
Small typo

2024-06-11 06:32 UTC, lwesterhof commented on admin/templates/admin/admin.html
> +    <link rel="stylesheet" href="{{ url_for('admin_bp.index', filename='css/stats.css') }}">
CSS include not needed for now.

2024-06-11 06:32 UTC, lwesterhof commented on general/templates/general/index.html
> +{% endblock content %}
Please configure Visual Studio Code insert a new line at the end of files.

2024-06-11 08:15 UTC, FuHsinyu commented on admin/static/admin/css/admin.css
I'll look into that the new layout! Thanks for suggestions.

2024-06-11 08:16 UTC, FuHsinyu commented on general/templates/general/index.html
> +{% endblock content %}
Good idea, will do.

2024-06-12 07:49 UTC, merged