add admin configuration of file formats
UtrechtUniversity/yoda-portal pull request #368
Opened 2024-10-07 11:57 UTC by leonidastri

As a functional admin I want to configure lists of preservable file formats  so that I ensure publication terms are up to date.

**Features added:**

As a functional admin the admin can navigate to Administration page and:

- they can now upload a new file of file formats.
- they can check the current list of files of file formats.
- they can choose a file of file formats and delete it. Then, the file is moved to trash folder, and there is a possibility to retrieve it in case of wrong deletion.

2024-10-07 12:07 UTC, leonidastri commented
This should be reviewed in combination with the following pr in yoda:
 https://github.com/UtrechtUniversity/yoda/pull/477

2024-10-08 11:31 UTC, lwesterhof requested changes

2024-10-08 11:31 UTC, lwesterhof commented on admin/templates/admin/admin.html
> +                            <label>Upload new File Formats:</label>
Singular: `Upload new file format list`

2024-10-08 11:31 UTC, lwesterhof commented on admin/templates/admin/admin.html
> +                            <button type="submit" class="btn btn-danger" id="delete-format-button" disabled>Delete File Formats</button>
Singular: `Delete file format list`

2024-10-08 11:31 UTC, lwesterhof commented on admin/templates/admin/admin.html
> +                    <h2 class="card-title">File Formats</h2>
Rename to `Preservable file formats` and add a short description. And maybe a link to the file format description in the technical documentation.

2024-10-08 13:03 UTC, leonidastri commented
Updated the code according to the comments!

2024-10-08 13:56 UTC, lwesterhof approved these changes
LGTM!

2024-10-08 13:57 UTC, merged