YDA-5946 - Modified form group with Yoda buttons to stick to the top of metadata form.
UtrechtUniversity/yoda-portal pull request #369
Opened 2024-10-08 11:26 UTC by kaur16

YDA-5946 - Modified form group with Yoda buttons to stick to the top of metadata form.

2024-10-18 14:39 UTC, kaur16 commented
Let me know what you think about this!

2024-10-21 06:53 UTC, lwesterhof requested changes

2024-10-21 06:53 UTC, lwesterhof commented on research/metadata-form/src/index.js
> +        return(<a class="btn btn-secondary" href={"/research/browse?dir=" + encodeURIComponent(path)}>Close</a>);
Can we also add a title to the close button?

2024-10-21 06:53 UTC, lwesterhof commented on research/metadata-form/src/index.js
>              </div>
We can pull the card header and card body into this render statement. 

Then it should look something like this:
![Screenshot 2024-10-21 at 08-49-48 Yoda - Dev - Research](https://github.com/user-attachments/assets/c9b6d878-8dd0-4994-91b9-e19368236333)

2024-10-29 11:17 UTC, lwesterhof requested changes

2024-10-29 11:17 UTC, lwesterhof commented on research/metadata-form/src/index.js
>                  // If maintenance banner is visible, add padding to metadata form header
Can we do the same for the "This is a development/testing/acceptance environment!" banner?

2024-10-31 15:53 UTC, lwesterhof approved these changes
LGTM!

2024-10-31 15:54 UTC, merged