Pyportal deposit css
UtrechtUniversity/yoda-portal pull request #45
Opened 2021-08-05 15:03 UTC by jdruiter

Deposit module UI:
* File-names word-wrap
* File browser wijder, geoptimaliseerd voor mogelijk lange filenames
* Thank you page is duidelijker over notifications
* Stepper voor stappen 1,2,3
* Meer kleine fixes

2021-08-10 07:08 UTC, lwesterhof requested changes

2021-08-10 07:08 UTC, lwesterhof commented on deposit/static/deposit/css/deposit.css
> +    margin-left: 10px;
Use Bootstrap spacing: https://getbootstrap.com/docs/4.0/utilities/spacing/

2021-08-10 07:08 UTC, lwesterhof commented on deposit/static/deposit/css/deposit.css
> +    padding-left: 10px;
Use Bootstrap spacing: https://getbootstrap.com/docs/4.0/utilities/spacing/

2021-08-10 18:29 UTC, jdruiter commented
Spacing classes van bootstrap gebruikt, en oude ongebruikte css weggehaalt

2021-08-11 06:04 UTC, lwesterhof approved these changes

2021-08-11 06:05 UTC, merged