WIP
UtrechtUniversity/yoda-portal pull request #93
Opened 2022-04-13 11:30 UTC by aucuparia

2022-04-13 11:44 UTC, lwesterhof reviewed
LGTM

2022-04-25 16:02 UTC, aucuparia commented
Rewrite of entire workflow is finished. Some polishing left, mostly Bootstrap stuff and code cleanup, but now would be a good time for first review.

2022-04-26 05:39 UTC, lwesterhof requested changes

2022-04-26 05:39 UTC, lwesterhof commented on datarequest/datarequest.py
> +    # Verify that uploaded file is a PDF
PDF verification is missing.

2022-04-26 05:39 UTC, lwesterhof commented on datarequest/datarequest.py
> +def human_readable_status(request_status):
May be nicer and more readable to use a Enum, for example: https://github.com/UtrechtUniversity/yoda-ruleset/blob/a0e4cfcf2fb5c6c68902cac3a3967ee8211a017e/util/constants.py#L122

2022-04-26 05:39 UTC, lwesterhof commented on datarequest/datarequest.py
> +    if not 'PM' in roles and not 'DM' in roles and not 'DAC' in roles and not 'OWN' in roles:
If we define this condition after the is_* declarations, we have a more readable conditon.

2022-04-26 05:39 UTC, lwesterhof commented on datarequest/datarequest.py
> +    api.call('datarequest_attachment_upload_permission', {'request_id': request_id, 'action': 'grant'})
Try and catch these API calls to handle errors?

2022-05-10 11:37 UTC, lwesterhof approved these changes
LGTM

2022-05-10 13:12 UTC, merged